//<auto-generated>
using Microsoft.EntityFrameworkCore.Migrations;

namespace LinkMe.Migrations
{
    public partial class AddedCountryTable : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Country",
                table: "LinkClicks");

            migrationBuilder.DropColumn(
                name: "CountryRegion",
                table: "LinkClicks");

            migrationBuilder.CreateTable(
                name: "Countries",
                columns: table => new
                {
                    CountryCode = table.Column<string>(maxLength: 15, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Countries", x => x.CountryCode);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Countries");

            migrationBuilder.AddColumn<string>(
                name: "Country",
                table: "LinkClicks",
                type: "nvarchar(50)",
                maxLength: 50,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "CountryRegion",
                table: "LinkClicks",
                type: "nvarchar(100)",
                maxLength: 100,
                nullable: true);
        }
    }
}
